In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 2.3007106 ,  0.17122126, -0.00601149, -2.31918209, -1.75027742,
        1.55680606, -2.18635583,  1.16378253, -0.85184607, -0.26739164])

In [6]:
B = np.random.randn(10)
B

array([ 0.45245217,  0.00459278, -0.74400007,  0.54650702, -0.51322558,
       -0.16817555, -0.87132113, -0.27701477, -0.37785727, -0.82843291])

In [7]:
# Binary Function 
np.add(A,B)

array([ 2.75316278,  0.17581404, -0.75001156, -1.77267507, -2.263503  ,
        1.38863051, -3.05767696,  0.88676775, -1.22970333, -1.09582455])

In [10]:
np.maximum(A,B)


array([ 2.3007106 ,  0.17122126, -0.00601149,  0.54650702, -0.51322558,
        1.55680606, -0.87132113,  1.16378253, -0.37785727, -0.26739164])

In [11]:
np.minimum(A,B)

array([ 0.45245217,  0.00459278, -0.74400007, -2.31918209, -1.75027742,
       -0.16817555, -2.18635583, -0.27701477, -0.85184607, -0.82843291])

In [13]:
import webbrowser
link = "www.naver.com"
webbrowser.open(link)

True